# Generated by Django 3.2.2 on 2021-07-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_locaisvisitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruzamento',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
